### PR TITLE
Hide translation install failures

### PR DESCRIPTION
**Pull request by grappler**
The normal output is helpful to see which languages have been installed and if they were downloaded or fetched from the cache.

See #22

### CODE REVIEW

**Comment by swissspidy** [comment]
I have tried that as well. I‘m not sure this really works. Let my upload my PR with a different approach.

**Comment by grappler** [comment]
I tested it and it worked for me but if you have a better idea...

**Comment by grappler** [comment]
> It was a bit confusing because I didn't know you were also working on this. But never mind.

I wanted to get a solution as it was affecting our projects. It was good to better understand the commands outputs. 

> But if you want to install a language for a certain plugin and it doesn't work, you don't get any feedback at all.

You would get the feedback when using `wp-cli` directly.

At the moment I think this is a bit cluttered and I worry about the performance of the extra command `wp plugin get --field=title`
```
      02 Installing language de_DE for plugin Advanced Custom Fields: Font Awesome
      02 Error: Language 'de_DE' not found.
      02 Installing language de_DE for plugin Advanced Custom Fields: Gravity Forms Field
      02 Error: Language 'de_DE' not found.
      02 Installing language de_DE for plugin Advanced Custom Fields PRO
      02 Warning: Ein unerwarteter Fehler ist aufgetreten. Es scheint etwas bei WordPress.org oder mit dieser Serverkonfiguration nicht zu stimmen. Sollte das Problem weiter best…
      02 Error: Language 'de_DE' not found.
      02 Installing language de_DE for plugin Compress JPEG & PNG images
      02 Using cached file '/home/schtifti/.wp-cli/cache/translation/plugin-tiny-compress-images-2.2.6-de_DE-1511180608.zip'...
      02 Unpacking the update...
      02 Installing the latest version...
      02 Translation updated successfully.
      02 Success: Language installed.
      02 Installing language de_DE for plugin Content Views
      02 Using cached file '/home/schtifti/.wp-cli/cache/translation/plugin-content-views-query-and-display-post-page-2.0.2-de_DE-1530016178.zip'...
      02 Unpacking the update...
      02 Installing the latest version...
      02 Translation updated successfully.
```

I would like to merge this a temp solution and later look for a better solution of maybe creating a new command to handle all themes/plugins.

**Comment by swissspidy** [comment]
> You would get the feedback when using wp-cli directly.

a) Not when doing this in a loop like in the script
b) You don't know which plugin is causing the error, so how would you know which one to test with wp-cli directly
c) You probably won't try it with wp-cli directly anyway

**Pull request merged**
